// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApbCszHnGtGm58HizrCbNKLu7c9mVTqdI',
    appId: '1:959802302309:web:37018b8bc1a5ecc665cb8c',
    messagingSenderId: '959802302309',
    projectId: 'auth-f21b7',
    authDomain: 'auth-f21b7.firebaseapp.com',
    storageBucket: 'auth-f21b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5mTfW90Najyfeem4dxkiStDkqSkAUdqI',
    appId: '1:959802302309:android:d3517cb767e7e90265cb8c',
    messagingSenderId: '959802302309',
    projectId: 'auth-f21b7',
    storageBucket: 'auth-f21b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw6m9sLl18X3NlXT_oKvGkWEjbFlGLeGU',
    appId: '1:959802302309:ios:d57a7938ae2c16a265cb8c',
    messagingSenderId: '959802302309',
    projectId: 'auth-f21b7',
    storageBucket: 'auth-f21b7.appspot.com',
    iosBundleId: 'com.example.authFlaxen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw6m9sLl18X3NlXT_oKvGkWEjbFlGLeGU',
    appId: '1:959802302309:ios:d57a7938ae2c16a265cb8c',
    messagingSenderId: '959802302309',
    projectId: 'auth-f21b7',
    storageBucket: 'auth-f21b7.appspot.com',
    iosBundleId: 'com.example.authFlaxen',
  );
}
